<?xml version="1.0" encoding="utf-8"?><Database Name="Dictionary" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=AMIR-MOSTAFA-HS;Initial Catalog=Dictionary;Integrated Security=True" SettingsObjectName="Dictionary_App.Properties.Settings" SettingsPropertyName="DictionaryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.WordsTable" Member="WordsTables">
    <Type Name="WordsTable">
      <Column Name="WordId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Word" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="PersianTranslate" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ArabicTranslate" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Pronounce" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="PronounceImage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Descriptions" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>